### ISSUE TITLE
Problematic return type of the `points` method

### ISSUE THREAD

**Issue by astro-ray** [dylannalex/curvipy#22]
The `Curve` class and its subclasses use the method `points` to return the curve points.
Currently, the return type of the `points` method is `list[int | float]`. 
But the return type should be `list[tuple[int | float, int | float]]`

**Comment by dylannalex** [comment]
Thanks for opening an Issue. Indeed, the return type of 'points()' method on 'Curve' classes is incorrect. I propose two ways of fixing this:

1. Declare a new type '_TPoint' at the start of '_curve.py' module:
```python
_TNumber = _Union[int, float]
_TVector = tuple[_TNumber, _TNumber]
_TPoint = tuple[_TNumber, _TNumber] # this is the new type
```
And replace 'points()' method return type with '_TPoint'. 

2. Rename the type '_TVector' to '_TNumber' and replace 'points()' method return type with '_TPoint'. 

Both '_TVector' and '_TNumber' are tuples of two numbers (i.e. int or float), so it would be a conceptual difference. '_TVector' is used in the 'ParametricFunction' to indicate that the parametric function parameter is a function that, given a real number, returns a _vector_.

```python
class ParametricFunction(Curve):
    def __init__(
        self, parametric_function: _Callable[[_TNumber], _TVector], interval: _Interval
    ):
```

Because of that, I think it is worth to have both '_TVector' and '_TPoint' defined despite them being the same type. What are your thoughts on this?

**Comment by astro-ray** [comment]
I say that we go with the first approach; that way, it will be more intuitive

**Comment by dylannalex** [comment]
Great work, @ritamsaha00! Thanks for contributing to Curvipy❤️
